---
engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 30
ratings:
  paths:
  - "**.rb"
  - "**.js"
  - "**.jsx"
  - "**.css"
exclude_paths:
- config/**/*
