---
engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
      languages:
        javascript:
ratings:
  paths:
  - "**.rb"
  - "**.js"
  - "**.jsx"
  - "**.css"
exclude_paths:
- config/**/*
